logging:
  level:
    ROOT: INFO
server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/entando-hackaton?useSSL=false&allowPublicKeyRetrieval=true
    username: entando-hackaton-user
    password: entando-hackaton-password
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
  security:
    oauth2:
      client:
        provider:
          oidc:
            issuer-uri: http://entando-hackaton-team-blue.apps.ocp4.eng-entando.com/auth/realms/entando
        registration:
          oidc:
            client-id: my-app

